init:
	terraform init

plan:
	terraform plan

apply:
	terraform apply -auto-approve

destroy:
	terraform destroy -auto-approve

eks:
	aws eks --region us-east-1 update-kubeconfig --name billerxchange_ml
