apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::378836287872:role/spark-irsa-test-role
  name: spark
  namespace: application
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:  
  name: ns-admin
  namespace: application
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sparkrolebinding
  namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-admin
subjects:
- kind: ServiceAccount
  name: spark
  namespace: application
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: application
spec:
  containers:
  - image: nginx
    name: nginx
  serviceAccountName: spark